Scaling means transforming features so they are on a similar range.

Some algorithms perform poorly when fetures have very diffent scale.

In [19]:
import pandas as pd
import numpy as np

In [20]:
data = {
    "EmployeeID":np.arange(1,101),
    "Age":np.random.randint(20,60,100),
    "Salary":np.random.randint(20000,100000,100)
   
}
df = pd.DataFrame(data)

In [21]:
df.head()

   EmployeeID  Age  Salary
0           1   36   84254
1           2   45   99036
2           3   40   55357
3           4   47   54290
4           5   22   58326

<h2>Standard Scaler</h2>

In [22]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
df[['age_transformed','Salary_transformed']] = scaler.fit_transform(df[['Age','Salary']])

In [23]:
df.head()

   EmployeeID  Age  Salary  age_transformed  Salary_transformed
0           1   36   84254        -0.332378            1.127387
1           2   45   99036         0.430735            1.832332
2           3   40   55357         0.006783           -0.250694
3           4   47   54290         0.600316           -0.301579
4           5   22   58326        -1.519443           -0.109104

In [24]:
avg = df['Salary'].mean()
std = df['Salary'].std()

In [25]:
df['Salary_manual'] = (df['Salary'] - avg)/std

In [27]:
df['Salary_Inverse_manual'] = (df['Salary_manual'] * std) + avg

In [28]:
df.head()

,EmployeeID,Age,Salary,age_transformed,Salary_transformed,Salary_manual,Salary_Inverse_manual
0,1,36,84254,-0.332378,1.127387,1.121736,84254.0
1,2,45,99036,0.430735,1.832332,1.823148,99036.0
2,3,40,55357,0.006783,-0.250694,-0.249438,55357.0
3,4,47,54290,0.600316,-0.301579,-0.300067,54290.0
4,5,22,58326,-1.519443,-0.109104,-0.108557,58326.0

In [29]:
df[['age_inverse','salary_inverse']] = scaler.inverse_transform(df[['age_transformed','Salary_transformed']])

In [30]:
df.head()

,EmployeeID,Age,Salary,age_transformed,Salary_transformed,Salary_manual,Salary_Inverse_manual,age_inverse,salary_inverse
0,1,36,84254,-0.332378,1.127387,1.121736,84254.0,36.0,84254.0
1,2,45,99036,0.430735,1.832332,1.823148,99036.0,45.0,99036.0
2,3,40,55357,0.006783,-0.250694,-0.249438,55357.0,40.0,55357.0
3,4,47,54290,0.600316,-0.301579,-0.300067,54290.0,47.0,54290.0
4,5,22,58326,-1.519443,-0.109104,-0.108557,58326.0,22.0,58326.0

<h2>Min Max Scaler</h2>

In [31]:
data = {
    "EmployeeID":np.arange(1,101),
    "Age":np.random.randint(20,60,100),
    "Salary":np.random.randint(20000,100000,100)
   
}
df = pd.DataFrame(data)

In [32]:
df.head()

   EmployeeID  Age  Salary
0           1   40   23770
1           2   58   48451
2           3   38   79425
3           4   51   81333
4           5   49   61919

In [33]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

df[['Age_scaled','Salary_scaled']] = scaler.fit_transform(df[['Age','Salary']])

In [34]:
df.head()

   EmployeeID  Age  Salary  Age_scaled  Salary_scaled
0           1   40   23770    0.512821       0.046858
1           2   58   48451    0.974359       0.356664
2           3   38   79425    0.461538       0.745462
3           4   51   81333    0.794872       0.769412
4           5   49   61919    0.743590       0.525720

In [35]:
xmin = df['Salary'].min()
xmax = df['Salary'].max()

In [36]:
df['Salary_Transformed'] = (df['Salary'] - xmin)/(xmax-xmin)

In [40]:
df['Salry_manual'] = df['Salary_Transformed']*(xmax-xmin)+xmin

In [41]:
df.head()

,EmployeeID,Age,Salary,Age_scaled,Salary_scaled,Salary_Transformed,Salry_manual
0,1,40,23770,0.512821,0.046858,0.046858,23770.0
1,2,58,48451,0.974359,0.356664,0.356664,48451.0
2,3,38,79425,0.461538,0.745462,0.745462,79425.0
3,4,51,81333,0.794872,0.769412,0.769412,81333.0
4,5,49,61919,0.743590,0.525720,0.525720,61919.0