In [1]:
import pandas as pd
import numpy as np
data = {
    'Name':['Rohan','Krish','Bob','Sohit','Kashish','Mayank'],
    'Age':[24,np.nan,34,23,np.nan,40],
    'Attendance':[100,90,80,np.nan,90,85]
}

df = pd.DataFrame(data)

In [3]:
df['Notes'] = [np.nan,"Good",np.nan,np.nan,np.nan,"Average"]

In [3]:
df

      Name   Age  Attendance    Notes
0    Rohan  24.0       100.0      NaN
1    Krish   NaN        90.0     Good
2      Bob  34.0        80.0      NaN
3    Sohit  23.0         NaN      NaN
4  Kashish   NaN        90.0      NaN
5   Mayank  40.0        85.0  Average

In [4]:
df['Age'].mean()

30.25

In [5]:
df['Age_filled'] = df['Age'].fillna(df['Age'].mean())

In [6]:
df

      Name   Age  Attendance    Notes  Age_filled
0    Rohan  24.0       100.0      NaN       24.00
1    Krish   NaN        90.0     Good       30.25
2      Bob  34.0        80.0      NaN       34.00
3    Sohit  23.0         NaN      NaN       23.00
4  Kashish   NaN        90.0      NaN       30.25
5   Mayank  40.0        85.0  Average       40.00

In [7]:
df['Attendance_filled'] = df['Attendance'].fillna(df['Attendance'].median())

In [8]:
df

      Name   Age  Attendance    Notes  Age_filled  Attendance_filled
0    Rohan  24.0       100.0      NaN       24.00              100.0
1    Krish   NaN        90.0     Good       30.25               90.0
2      Bob  34.0        80.0      NaN       34.00               80.0
3    Sohit  23.0         NaN      NaN       23.00               90.0
4  Kashish   NaN        90.0      NaN       30.25               90.0
5   Mayank  40.0        85.0  Average       40.00               85.0

In [9]:
df['Notes_filled'] = df['Notes'].fillna("Not Given")

In [10]:
df

,Name,Age,Attendance,Notes,Age_filled,Attendance_filled,Notes_filled
0,Rohan,24.0,100.0,NaN,24.00,100.0,Not Given
1,Krish,NaN,90.0,Good,30.25,90.0,Good
2,Bob,34.0,80.0,NaN,34.00,80.0,Not Given
3,Sohit,23.0,NaN,NaN,23.00,90.0,Not Given
4,Kashish,NaN,90.0,NaN,30.25,90.0,Not Given
5,Mayank,40.0,85.0,Average,40.00,85.0,Average

In [11]:
df['Age_ffill'] = df['Age'].ffill()

In [12]:
df

,Name,Age,Attendance,Notes,Age_filled,Attendance_filled,Notes_filled,Age_ffill
0,Rohan,24.0,100.0,NaN,24.00,100.0,Not Given,24.0
1,Krish,NaN,90.0,Good,30.25,90.0,Good,24.0
2,Bob,34.0,80.0,NaN,34.00,80.0,Not Given,34.0
3,Sohit,23.0,NaN,NaN,23.00,90.0,Not Given,23.0
4,Kashish,NaN,90.0,NaN,30.25,90.0,Not Given,23.0
5,Mayank,40.0,85.0,Average,40.00,85.0,Average,40.0

In [13]:
df['Attendance_bfill'] = df['Attendance'].bfill()

In [15]:
df['Notes_bfill'] = df['Notes'].bfill()

In [16]:
df

,Name,Age,Attendance,Notes,Age_filled,Attendance_filled,Notes_filled,Age_ffill,Attendance_bfill,Notes_bfill
0,Rohan,24.0,100.0,NaN,24.00,100.0,Not Given,24.0,100.0,Good
1,Krish,NaN,90.0,Good,30.25,90.0,Good,24.0,90.0,Good
2,Bob,34.0,80.0,NaN,34.00,80.0,Not Given,34.0,80.0,Average
3,Sohit,23.0,NaN,NaN,23.00,90.0,Not Given,23.0,90.0,Average
4,Kashish,NaN,90.0,NaN,30.25,90.0,Not Given,23.0,90.0,Average
5,Mayank,40.0,85.0,Average,40.00,85.0,Average,40.0,85.0,Average

<h3>Numerical Value Imputation</h3>

In [5]:
from sklearn.impute import SimpleImputer

<h4>handling with mean</h4>

In [7]:
imputer = SimpleImputer(strategy='mean')

df[['Age_filled'] ]= imputer.fit_transform(df[['Age']])

In [8]:
df

      Name   Age  Attendance    Notes  Age_filled
0    Rohan  24.0       100.0      NaN       24.00
1    Krish   NaN        90.0     Good       30.25
2      Bob  34.0        80.0      NaN       34.00
3    Sohit  23.0         NaN      NaN       23.00
4  Kashish   NaN        90.0      NaN       30.25
5   Mayank  40.0        85.0  Average       40.00

</h4>Handling with median</h4>

In [10]:
median_imputer = SimpleImputer(strategy='median')

df[['Attendance_filled']] = median_imputer.fit_transform(df[['Attendance']])

In [11]:
df

      Name   Age  Attendance    Notes  Age_filled  Attendance_filled
0    Rohan  24.0       100.0      NaN       24.00              100.0
1    Krish   NaN        90.0     Good       30.25               90.0
2      Bob  34.0        80.0      NaN       34.00               80.0
3    Sohit  23.0         NaN      NaN       23.00               90.0
4  Kashish   NaN        90.0      NaN       30.25               90.0
5   Mayank  40.0        85.0  Average       40.00               85.0

<h4>Handling with Constant value </h4>

In [12]:
df['Age_constant']= df['Age'].fillna(20)

In [13]:
df

,Name,Age,Attendance,Notes,Age_filled,Attendance_filled,Age_constant
0,Rohan,24.0,100.0,NaN,24.00,100.0,24.0
1,Krish,NaN,90.0,Good,30.25,90.0,20.0
2,Bob,34.0,80.0,NaN,34.00,80.0,34.0
3,Sohit,23.0,NaN,NaN,23.00,90.0,23.0
4,Kashish,NaN,90.0,NaN,30.25,90.0,20.0
5,Mayank,40.0,85.0,Average,40.00,85.0,40.0

<h4>End of distribution</h4>

In [14]:
val = df['Age'].mean() + 3 * df['Age'].std()

df['Age_endDist'] = df['Age'].fillna(val)

In [15]:
df

,Name,Age,Attendance,Notes,Age_filled,Attendance_filled,Age_constant,Age_endDist
0,Rohan,24.0,100.0,NaN,24.00,100.0,24.0,24.000000
1,Krish,NaN,90.0,Good,30.25,90.0,20.0,54.790782
2,Bob,34.0,80.0,NaN,34.00,80.0,34.0,34.000000
3,Sohit,23.0,NaN,NaN,23.00,90.0,23.0,23.000000
4,Kashish,NaN,90.0,NaN,30.25,90.0,20.0,54.790782
5,Mayank,40.0,85.0,Average,40.00,85.0,40.0,40.000000

<h3>Categorical Value Imputation</h3>

<h4>Most Frequent</h4>

In [16]:
ct_imputer = SimpleImputer(strategy='most_frequent')

df[['Notes_filled']] = ct_imputer.fit_transform(df[['Notes']])

In [17]:
df

,Name,Age,Attendance,Notes,Age_filled,Attendance_filled,Age_constant,Age_endDist,Notes_filled
0,Rohan,24.0,100.0,NaN,24.00,100.0,24.0,24.000000,Average
1,Krish,NaN,90.0,Good,30.25,90.0,20.0,54.790782,Good
2,Bob,34.0,80.0,NaN,34.00,80.0,34.0,34.000000,Average
3,Sohit,23.0,NaN,NaN,23.00,90.0,23.0,23.000000,Average
4,Kashish,NaN,90.0,NaN,30.25,90.0,20.0,54.790782,Average
5,Mayank,40.0,85.0,Average,40.00,85.0,40.0,40.000000,Average

<h4>Fill with constant</h4>

In [18]:
df['Notes_rev'] = df['Notes'].fillna("Missing")

In [19]:
df

,Name,Age,Attendance,Notes,Age_filled,Attendance_filled,Age_constant,Age_endDist,Notes_filled,Notes_rev
0,Rohan,24.0,100.0,NaN,24.00,100.0,24.0,24.000000,Average,Missing
1,Krish,NaN,90.0,Good,30.25,90.0,20.0,54.790782,Good,Good
2,Bob,34.0,80.0,NaN,34.00,80.0,34.0,34.000000,Average,Missing
3,Sohit,23.0,NaN,NaN,23.00,90.0,23.0,23.000000,Average,Missing
4,Kashish,NaN,90.0,NaN,30.25,90.0,20.0,54.790782,Average,Missing
5,Mayank,40.0,85.0,Average,40.00,85.0,40.0,40.000000,Average,Average

<h1>Multivariate Imputation</h1>

<h3>KNN - K Nearest Neighbors</h3>

In [20]:
import numpy as np
import pandas as pd

from sklearn.impute import KNNImputer
from sklearn.preprocessing import StandardScaler

In [21]:
data = {
    'Experience':[1,2,3,10,11,12,20,21,np.nan],
    'Salary':[45000,50000,np.nan,110000,120000,125000,200000,np.nan,210000],
    'Age':[22,24,23,35,np.nan,38,50,52,51]
}

In [22]:
df = pd.DataFrame(data)
df

   Experience    Salary   Age
0         1.0   45000.0  22.0
1         2.0   50000.0  24.0
2         3.0       NaN  23.0
3        10.0  110000.0  35.0
4        11.0  120000.0   NaN
5        12.0  125000.0  38.0
6        20.0  200000.0  50.0
7        21.0       NaN  52.0
8         NaN  210000.0  51.0

In [23]:
scaler = StandardScaler()

df_scaled = scaler.fit_transform(df)
df_scaled = pd.DataFrame(df_scaled,columns=df.columns)
df_scaled

   Experience    Salary       Age
0   -1.242118 -1.300386 -1.222266
1   -1.104105 -1.216875 -1.057928
2   -0.966092       NaN -1.140097
3    0.000000 -0.214743 -0.154067
4    0.138013 -0.047721       NaN
5    0.276026  0.035790  0.092440
6    1.380131  1.288456  1.078470
7    1.518144       NaN  1.242808
8         NaN  1.455478  1.160639

In [24]:
imputer = KNNImputer(n_neighbors=3)

In [25]:
df_imputed = imputer.fit_transform(df_scaled)

In [29]:
df_inverse = scaler.inverse_transform(df_imputed)
df_final = pd.DataFrame(df_inverse,columns=df.columns)
df_final

   Experience         Salary   Age
0    1.000000   45000.000000  22.0
1    2.000000   50000.000000  24.0
2    3.000000   68333.333333  23.0
3   10.000000  110000.000000  35.0
4   11.000000  120000.000000  32.0
5   12.000000  125000.000000  38.0
6   20.000000  200000.000000  50.0
7   21.000000  178333.333333  52.0
8   17.666667  210000.000000  51.0

<h3>Iterative Imputer</h3>

In [30]:
from sklearn.experimental import enable_iterative_imputer

from sklearn.impute import IterativeImputer
from sklearn.preprocessing import StandardScaler

In [32]:
np.random.seed(42)

age = np.random.randint(20,60,100)
income = (age*20) + np.random.normal(0,5000,100)

df = pd.DataFrame({'Age':age,'Income':income})

In [44]:
df.head()

    Age       Income
0  58.0   271.339394
1   NaN -1091.916543
2   NaN  6578.581724
3   NaN -3951.039697
4   NaN  4973.977096

In [35]:
df.iloc[1:10,0] = np.nan
df.iloc[20:30,1] = np.nan

In [36]:
df.isnull().sum()

Age        9
Income    10
dtype: int64

In [37]:
scaler = StandardScaler()
df_scaled = pd.DataFrame(scaler.fit_transform(df),columns= df.columns)

In [45]:
df_scaled.head(20)

         Age    Income
0   1.641162 -0.203928
1        NaN -0.479100
2        NaN  1.069185
3        NaN -1.056212
4        NaN  0.745296
5        NaN  0.274751
6        NaN -1.152718
7        NaN -0.165649
8        NaN  0.844372
9        NaN  0.665364
10  0.358123  1.424155
11  1.384554  0.304645
12  1.726697  3.382963
13  0.358123 -1.014008
14 -1.438131 -0.572208
15  0.187051 -0.154608
16 -1.523667 -1.605789
17  0.358123  0.967024
18  0.871338  0.851002
19  1.555626 -0.009413

In [43]:
it_imputer = IterativeImputer(max_iter=10)

df_imputed = it_imputer.fit_transform(df_scaled)

pd.DataFrame(scaler.inverse_transform(df_imputed),columns=df.columns).head()

         Age       Income
0  58.000000   271.339394
1  37.724775 -1091.916543
2  41.299180  6578.581724
3  36.392442 -3951.039697
4  40.551444  4973.977096