<center><h1 style="color:cyan;"><strong>Pandas Tutorial</strong></h1></center>

Pandas is a Python library for data analysis and data manipulation tasks. It works with many different types of data sets such as comma-separated values (CSV) files, Excel files, extensible markup language (XML) files, JavaScript object notation (JSON) files and relational database tables.

In pandas we are given type of datastructure

- 1D datastructure = Series
- 2D datastructure = DataFrame

column -> field -> label
row -> record

In [2]:
d = {
        "name":[
            "Mr. Owen Harris",
            "Mr. William Henry",
            " Miss Elizabeth",
        ],
         "Age":[22, 35, 58],
        "Gender":["male", "male", "female"],
}

In [3]:
print(type(d))

<class 'dict'>

In [3]:
!pip3 install pandas

Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (3.0.0)
Requirement already satisfied: numpy>=2.3.3 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/dhruv/Library/Python/3.14/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/dhruv/Library/Python/3.14/lib/python/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

{
    "name":"Rohit",
    "Age",23,
    "salary":45000
},
{
    "name":"Shreya",
    "Age",22,
    "salary":38000
}

In [1]:
import pandas as pd

1D datastructure(Series)

In [5]:
sr = pd.Series([34,45,23,65])

In [8]:
print(type(sr))

<class 'pandas.Series'>

2D datastructure(DataFrame)

In [19]:
df = pd.DataFrame(d)

In [20]:
print(df)
print(type(df))

                Name  Age     Sex
0    Mr. Owen Harris   22    male
1  Mr. William Henry   35    male
2     Miss Elizabeth   58  female
<class 'pandas.DataFrame'>

load csv in pandas

In [5]:
df = pd.read_csv('fact_sales.csv')

In [6]:
df.head(10)

,order_number,product_key,customer_key,order_date,shipping_date,due_date,sales_amount,quantity,price
0,SO54496,282,5400,2013-03-16,2013-03-23,2013-03-28,25,1,25
1,SO54496,289,5400,2013-03-16,2013-03-23,2013-03-28,5,1,5
2,SO54496,259,5400,2013-03-16,2013-03-23,2013-03-28,2,1,2
3,SO54497,174,9281,2013-03-16,2013-03-23,2013-03-28,22,1,22
4,SO54497,280,9281,2013-03-16,2013-03-23,2013-03-28,9,1,9
5,SO54498,174,4825,2013-03-16,2013-03-23,2013-03-28,22,1,22
6,SO54498,277,4825,2013-03-16,2013-03-23,2013-03-28,54,1,54
7,SO54499,289,4286,2013-03-16,2013-03-23,2013-03-28,5,1,5
8,SO54499,246,4286,2013-03-16,2013-03-23,2013-03-28,35,1,35
9,SO54500,289,1472,2013-03-16,2013-03-23,2013-03-28,5,1,5

In [7]:
df.tail(15)

,order_number,product_key,customer_key,order_date,shipping_date,due_date,sales_amount,quantity,price
60383,SO54490,248,9280,2013-03-16,2013-03-23,2013-03-28,50,1,50
60384,SO54490,235,9280,2013-03-16,2013-03-23,2013-03-28,24,1,24
60385,SO54491,295,1166,2013-03-16,2013-03-23,2013-03-28,5,1,5
60386,SO54491,168,1166,2013-03-16,2013-03-23,2013-03-28,8,1,8
60387,SO54492,295,5886,2013-03-16,2013-03-23,2013-03-28,5,1,5
60388,SO54492,246,5886,2013-03-16,2013-03-23,2013-03-28,35,1,35
60389,SO54493,289,4881,2013-03-16,2013-03-23,2013-03-28,5,1,5
60390,SO54493,168,4881,2013-03-16,2013-03-23,2013-03-28,8,1,8
60391,SO54493,260,4881,2013-03-16,2013-03-23,2013-03-28,120,1,120
60392,SO54494,289,11279,2013-03-16,2013-03-23,2013-03-28,5,1,5
60393,SO54494,259,11279,2013-03-16,2013-03-23,2013-03-28,2,1,2
60394,SO54495,289,3750,2013-03-16,2013-03-23,2013-03-28,5,1,5
60395,SO54495,244,3750,2013-03-16,2013-03-23,2013-03-28,35,1,35
60396,SO54495,248,3750,2013-03-16,2013-03-23,2013-03-28,50,1,50
60397,SO54495,166,3750,2013-03-16,2013-03-23,2013-03-28,9,1,9

In [32]:
print(df.columns)

Index(['order_number', 'product_key', 'customer_key', 'order_date',
       'shipping_date', 'due_date', 'sales_amount', 'quantity', 'price'],
      dtype='str')

In [33]:
df.dtypes

order_number       str
product_key      int64
customer_key     int64
order_date         str
shipping_date      str
due_date           str
sales_amount     int64
quantity         int64
price            int64
dtype: object

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 60398 entries, 0 to 60397
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_number   60398 non-null  str
 1   product_key    60398 non-null  int64
 2   customer_key   60398 non-null  int64
 3   order_date     60379 non-null  str
 4   shipping_date  60398 non-null  str
 5   due_date       60398 non-null  str
 6   sales_amount   60398 non-null  int64
 7   quantity       60398 non-null  int64
 8   price          60398 non-null  int64
dtypes: int64(5), str(4)
memory usage: 4.1 MB

In [12]:
df['sales_amount'].values.sum()

np.int64(29356250)

In [13]:
df.ndim

2

In [14]:
df.size

543582

In [15]:
df.shape

(60398, 9)

In [16]:
df.head().memory_usage

<bound method DataFrame.memory_usage of   order_number  product_key  customer_key  order_date shipping_date  \
0      SO54496          282          5400  2013-03-16    2013-03-23
1      SO54496          289          5400  2013-03-16    2013-03-23
2      SO54496          259          5400  2013-03-16    2013-03-23
3      SO54497          174          9281  2013-03-16    2013-03-23
4      SO54497          280          9281  2013-03-16    2013-03-23

     due_date  sales_amount  quantity  price
0  2013-03-28            25         1     25
1  2013-03-28             5         1      5
2  2013-03-28             2         1      2
3  2013-03-28            22         1     22
4  2013-03-28             9         1      9  >

In [17]:
df['sales_amount'].astype('float64')

0        25.0
1         5.0
2         2.0
3        22.0
4         9.0
         ...
60393     2.0
60394     5.0
60395    35.0
60396    50.0
60397     9.0
Name: sales_amount, Length: 60398, dtype: float64

In [18]:
df.loc[0]

order_number        SO54496
product_key             282
customer_key           5400
order_date       2013-03-16
shipping_date    2013-03-23
due_date         2013-03-28
sales_amount             25
quantity                  1
price                    25
Name: 0, dtype: object

In [54]:
df.head(2)

,order_number,product_key,customer_key,order_date,shipping_date,due_date,sales_amount,quantity,price
0,SO54496,282,5400,2013-03-16,2013-03-23,2013-03-28,25,1,25
1,SO54496,289,5400,2013-03-16,2013-03-23,2013-03-28,5,1,5

In [52]:
df1 = pd.DataFrame(
    [[1, 2], [4, 5], [7, 8]],
    index=["cobra", "viper", "sidewinder"],
    columns=["max_speed", "shield"],
)

In [53]:
df1

            max_speed  shield
cobra               1       2
viper               4       5
sidewinder          7       8

In [58]:
df1.loc["cobra"]

max_speed    1
shield       2
Name: cobra, dtype: int64

In [60]:
df1.iloc[0]

max_speed    1
shield       2
Name: cobra, dtype: int64

In [61]:
df2 = pd.DataFrame({
    'col1':[1,2],
    'col2':[3,4]
})

In [66]:
df2.insert(1,"col4",[9,0])

In [67]:
df2

   col3  col4  col1  col2
0     5     9     1     3
1     6     0     2     4

Slicing The data

In [23]:
df[12000:12079]

,order_number,product_key,customer_key,order_date,shipping_date,due_date,sales_amount,quantity,price
12000,SO59826,290,12487,2013-06-09,2013-06-16,2013-06-21,4,1,4
12001,SO59826,245,12487,2013-06-09,2013-06-16,2013-06-21,35,1,35
12002,SO59827,136,2085,2013-06-09,2013-06-16,2013-06-21,1701,1,1701
12003,SO59827,246,2085,2013-06-09,2013-06-16,2013-06-21,35,1,35
12004,SO59827,275,2085,2013-06-09,2013-06-16,2013-06-21,54,1,54
...,...,...,...,...,...,...,...,...,...
12074,SO59855,246,14885,2013-06-10,2013-06-17,2013-06-22,35,1,35
12075,SO59856,289,11265,2013-06-10,2013-06-17,2013-06-22,5,1,5
12076,SO59856,246,11265,2013-06-10,2013-06-17,2013-06-22,35,1,35
12077,SO59856,250,11265,2013-06-10,2013-06-17,2013-06-22,50,1,50
12078,SO59857,290,3177,2013-06-10,2013-06-17,2013-06-22,4,1,4

In [29]:
df[['order_number','order_date','due_date','sales_amount','quantity']][:10]

  order_number  order_date    due_date  sales_amount  quantity
0      SO54496  2013-03-16  2013-03-28            25         1
1      SO54496  2013-03-16  2013-03-28             5         1
2      SO54496  2013-03-16  2013-03-28             2         1
3      SO54497  2013-03-16  2013-03-28            22         1
4      SO54497  2013-03-16  2013-03-28             9         1
5      SO54498  2013-03-16  2013-03-28            22         1
6      SO54498  2013-03-16  2013-03-28            54         1
7      SO54499  2013-03-16  2013-03-28             5         1
8      SO54499  2013-03-16  2013-03-28            35         1
9      SO54500  2013-03-16  2013-03-28             5         1

In [33]:
df.loc[:4]

,order_number,product_key,customer_key,order_date,shipping_date,due_date,sales_amount,quantity,price
0,SO54496,282,5400,2013-03-16,2013-03-23,2013-03-28,25,1,25
1,SO54496,289,5400,2013-03-16,2013-03-23,2013-03-28,5,1,5
2,SO54496,259,5400,2013-03-16,2013-03-23,2013-03-28,2,1,2
3,SO54497,174,9281,2013-03-16,2013-03-23,2013-03-28,22,1,22
4,SO54497,280,9281,2013-03-16,2013-03-23,2013-03-28,9,1,9

In [34]:
import numpy as np

In [37]:
df2 = pd.DataFrame(np.random.randn(6,4),index=['a','b','c','d','e','f'],columns=['col1','col2','col3','col4'])

In [38]:
df2

       col1      col2      col3      col4
a  0.200242 -0.511550 -0.834136  1.095044
b  1.727890  1.258245  0.860370  0.040165
c -0.027525  0.811863  0.189589  0.599622
d  0.236374 -0.452835  0.259419  0.597335
e -0.672102  0.398713 -1.257003  0.552909
f  0.239074 -0.799889  0.962549  0.703373

In [41]:
df2.loc[:'b']

       col1      col2      col3      col4
a  0.200242 -0.511550 -0.834136  1.095044
b  1.727890  1.258245  0.860370  0.040165

In [47]:
def check(df):
    return df['col1']>0

In [49]:
df2.loc[lambda df:df['col1']>0,:].loc[:'d']

       col1      col2      col3      col4
a  0.200242 -0.511550 -0.834136  1.095044
b  1.727890  1.258245  0.860370  0.040165
d  0.236374 -0.452835  0.259419  0.597335

In [61]:
df['month'].value_counts()

month
12.0    6239
10.0    5832
11.0    5756
6.0     5573
8.0     5335
7.0     5105
9.0     5070
5.0     4780
3.0     4449
4.0     4355
1.0     4028
2.0     3857
Name: count, dtype: int64

In [55]:
df['order_date'] = pd.to_datetime(df['order_date'])
df['shipping_date'] = pd.to_datetime(df['shipping_date'])

In [60]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 60398 entries, 0 to 60397
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_number   60398 non-null  str
 1   product_key    60398 non-null  int64
 2   customer_key   60398 non-null  int64
 3   order_date     60379 non-null  datetime64[us]
 4   shipping_date  60398 non-null  datetime64[us]
 5   due_date       60398 non-null  str
 6   sales_amount   60398 non-null  int64
 7   quantity       60398 non-null  int64
 8   price          60398 non-null  int64
 9   month          60379 non-null  float64
dtypes: datetime64[us](2), float64(1), int64(5), str(2)
memory usage: 4.6 MB

In [ ]:
df['month'] = df['order_date'].dt.month

In [63]:
df['year'] = df['order_date'].dt.year

In [66]:
df.groupby(['year','month'])['sales_amount'].sum()

year    month
2010.0  12.0       43419
2011.0  1.0       469795
        2.0       466307
        3.0       485165
        4.0       502042
        5.0       561647
        6.0       737793
        7.0       596710
        8.0       614516
        9.0       603047
        10.0      708164
        11.0      660507
        12.0      669395
2012.0  1.0       495363
        2.0       506992
        3.0       373478
        4.0       400324
        5.0       358866
        6.0       555142
        7.0       444533
        8.0       523887
        9.0       486149
        10.0      535125
        11.0      537918
        12.0      624454
2013.0  1.0       857758
        2.0       771218
        3.0      1049732
        4.0      1045860
        5.0      1284456
        6.0      1642948
        7.0      1371595
        8.0      1545910
        9.0      1447324
        10.0     1673261
        11.0     1780688
        12.0     1874128
2014.0  1.0        45642
Name: sales_amount, dtype: int64

In [ ]:
df.groupby(['year','month'])[['sales_amount','quantity']].agg(['sum','mean','std'])

             sales_amount                           quantity            \
                      sum         mean          std      sum      mean
year   month
2010.0 12.0         43419  3101.357143  1021.484185       14  1.000000
2011.0 1.0         469795  3262.465278   847.387247      144  1.000000
       2.0         466307  3238.243056   872.300738      144  1.000000
       3.0         485165  3234.433333   911.090743      150  1.000000
       4.0         502042  3197.719745   932.829256      157  1.000000
       5.0         561647  3227.856322   890.964916      174  1.000000
       6.0         737793  3207.795652   919.756849      230  1.000000
       7.0         596710  3173.989362   952.208898      188  1.000000
       8.0         614516  3184.020725   962.980989      193  1.000000
       9.0         603047  3259.713514   846.370633      185  1.000000
       10.0        708164  3204.361991   919.851374      221  1.000000
       11.0        660507  3175.514423   941.589826      208  1.000000
       12.0        669395  3015.292793  1012.016727      222  1.000000
2012.0 1.0         495363  1965.726190   555.886894      252  1.000000
       2.0         506992  1949.969231   551.175051      260  1.000000
       3.0         373478  1761.688679   646.353129      212  1.000000
       4.0         400324  1827.963470   603.939733      219  1.000000
       5.0         358866  1733.652174   659.028938      207  1.000000
       6.0         555142  1745.729560   607.942397      318  1.000000
       7.0         444533  1807.044715   600.444531      246  1.000000
       8.0         523887  1781.928571   609.506418      294  1.000000
       9.0         486149  1807.245353   598.584998      269  1.000000
       10.0        535125  1709.664537   620.895563      313  1.000000
       11.0        537918  1660.240741   623.588753      324  1.000000
       12.0        624454  1292.865424   940.077429      483  1.000000
2013.0 1.0         857758   516.099880   866.128704     1677  1.009025
       2.0         771218   223.347234   588.819707     3454  1.000290
       3.0        1049732   256.846587   633.559245     4087  1.000000
       4.0        1045860   262.844936   644.619329     3979  1.000000
       5.0        1284456   291.988179   672.216794     4400  1.000227
       6.0        1642948   326.954826   699.011744     5025  1.000000
       7.0        1371595   293.640548   677.689757     4673  1.000428
       8.0        1545910   318.875825   702.520698     4848  1.000000
       9.0        1447324   313.545061   689.252364     4616  1.000000
       10.0       1673261   315.828803   686.474295     5304  1.001133
       11.0       1780688   340.866769   711.496681     5224  1.000000
       12.0       1874128   339.515942   710.348943     5520  1.000000
2014.0 1.0          45642    23.168528    23.072963     1970  1.000000


                   std
year   month
2010.0 12.0   0.000000
2011.0 1.0    0.000000
       2.0    0.000000
       3.0    0.000000
       4.0    0.000000
       5.0    0.000000
       6.0    0.000000
       7.0    0.000000
       8.0    0.000000
       9.0    0.000000
       10.0   0.000000
       11.0   0.000000
       12.0   0.000000
2012.0 1.0    0.000000
       2.0    0.000000
       3.0    0.000000
       4.0    0.000000
       5.0    0.000000
       6.0    0.000000
       7.0    0.000000
       8.0    0.000000
       9.0    0.000000
       10.0   0.000000
       11.0   0.000000
       12.0   0.000000
2013.0 1.0    0.243970
       2.0    0.017018
       3.0    0.000000
       4.0    0.000000
       5.0    0.015077
       6.0    0.000000
       7.0    0.020690
       8.0    0.000000
       9.0    0.000000
       10.0   0.051398
       11.0   0.000000
       12.0   0.000000
2014.0 1.0    0.000000

In [78]:
df.where(df['quantity']>0)

,order_number,product_key,customer_key,order_date,shipping_date,due_date,sales_amount,quantity,price,month,year
0,SO54496,282,5400,2013-03-16,2013-03-23,2013-03-28,25,1,25,3.0,2013.0
1,SO54496,289,5400,2013-03-16,2013-03-23,2013-03-28,5,1,5,3.0,2013.0
2,SO54496,259,5400,2013-03-16,2013-03-23,2013-03-28,2,1,2,3.0,2013.0
3,SO54497,174,9281,2013-03-16,2013-03-23,2013-03-28,22,1,22,3.0,2013.0
4,SO54497,280,9281,2013-03-16,2013-03-23,2013-03-28,9,1,9,3.0,2013.0
...,...,...,...,...,...,...,...,...,...,...,...
60393,SO54494,259,11279,2013-03-16,2013-03-23,2013-03-28,2,1,2,3.0,2013.0
60394,SO54495,289,3750,2013-03-16,2013-03-23,2013-03-28,5,1,5,3.0,2013.0
60395,SO54495,244,3750,2013-03-16,2013-03-23,2013-03-28,35,1,35,3.0,2013.0
60396,SO54495,248,3750,2013-03-16,2013-03-23,2013-03-28,50,1,50,3.0,2013.0
60397,SO54495,166,3750,2013-03-16,2013-03-23,2013-03-28,9,1,9,3.0,2013.0

In [79]:
df['quantity'].value_counts()

quantity
1     60387
2         7
4         1
3         1
5         1
10        1
Name: count, dtype: int64

In [81]:
df.where(df['month']==12).value_counts()

order_number  product_key  customer_key  order_date  shipping_date  due_date    sales_amount  quantity  price   month  year
SO72061       112.0        2036.0        2013-12-01  2013-12-08     2013-12-13  565.0         1.0       565.0   12.0   2013.0    1
              104.0        2036.0        2013-12-01  2013-12-08     2013-12-13  10.0          1.0       10.0    12.0   2013.0    1
              166.0        2036.0        2013-12-01  2013-12-08     2013-12-13  9.0           1.0       9.0     12.0   2013.0    1
              295.0        2036.0        2013-12-01  2013-12-08     2013-12-13  5.0           1.0       5.0     12.0   2013.0    1
SO72062       112.0        5685.0        2013-12-01  2013-12-08     2013-12-13  565.0         1.0       565.0   12.0   2013.0    1
                                                                                                                                ..
SO51245       166.0        1125.0        2012-12-31  2013-01-07     2013-01-12  9.0           1.0       9.0     12.0   2012.0    1
SO51246       159.0        14626.0       2012-12-31  2013-01-07     2013-01-12  2384.0        1.0       2384.0  12.0   2012.0    1
              105.0        14626.0       2012-12-31  2013-01-07     2013-01-12  9.0           1.0       9.0     12.0   2012.0    1
              295.0        14626.0       2012-12-31  2013-01-07     2013-01-12  5.0           1.0       5.0     12.0   2012.0    1
              246.0        14626.0       2012-12-31  2013-01-07     2013-01-12  35.0          1.0       35.0    12.0   2012.0    1
Name: count, Length: 6239, dtype: int64

In [83]:
df.pivot_table(index="month",columns='year',values=["sales_amount","quantity"])

      quantity                                sales_amount               \
year    2010.0 2011.0 2012.0    2013.0 2014.0       2010.0       2011.0
month
1.0        NaN    1.0    1.0  1.009025    1.0          NaN  3262.465278
2.0        NaN    1.0    1.0  1.000290    NaN          NaN  3238.243056
3.0        NaN    1.0    1.0  1.000000    NaN          NaN  3234.433333
4.0        NaN    1.0    1.0  1.000000    NaN          NaN  3197.719745
5.0        NaN    1.0    1.0  1.000227    NaN          NaN  3227.856322
6.0        NaN    1.0    1.0  1.000000    NaN          NaN  3207.795652
7.0        NaN    1.0    1.0  1.000428    NaN          NaN  3173.989362
8.0        NaN    1.0    1.0  1.000000    NaN          NaN  3184.020725
9.0        NaN    1.0    1.0  1.000000    NaN          NaN  3259.713514
10.0       NaN    1.0    1.0  1.001133    NaN          NaN  3204.361991
11.0       NaN    1.0    1.0  1.000000    NaN          NaN  3175.514423
12.0       1.0    1.0    1.0  1.000000    NaN  3101.357143  3015.292793


year        2012.0      2013.0     2014.0
month
1.0    1965.726190  516.099880  23.168528
2.0    1949.969231  223.347234        NaN
3.0    1761.688679  256.846587        NaN
4.0    1827.963470  262.844936        NaN
5.0    1733.652174  291.988179        NaN
6.0    1745.729560  326.954826        NaN
7.0    1807.044715  293.640548        NaN
8.0    1781.928571  318.875825        NaN
9.0    1807.245353  313.545061        NaN
10.0   1709.664537  315.828803        NaN
11.0   1660.240741  340.866769        NaN
12.0   1292.865424  339.515942        NaN

<h2><strong>concat</strong></h2>

In [33]:
df1 = pd.DataFrame({
    "A":[1,2,3],
    "B":[4,5,6],
    "C":[7,8,9]
},index=[1,2,3]
)

df2 = pd.DataFrame({
    "D":[1,2,3],
    "B":[7,6,5],
    "C":[4,3,2]
},index=[4,5,6]
)

In [23]:
arr = [df1,df2]

pd.concat(arr,axis=0)

   A  B  C
1  1  4  7
2  2  5  8
3  3  6  9
4  1  7  4
5  2  6  3
6  3  5  2

<h2><strong>Join</strong></h2>

In [34]:
pd.concat(arr,axis=0,join='outer')

   A  B  C
1  1  4  7
2  2  5  8
3  3  6  9
4  1  7  4
5  2  6  3
6  3  5  2

In [35]:
fact = pd.read_csv("fact_sales.csv")
customers = pd.read_csv("dim_customers.csv")
products = pd.read_csv("dim_products.csv")

In [67]:
data = pd.merge(fact,customers,how="inner",on="customer_key")[["order_number","product_key","order_date","shipping_date","sales_amount","quantity","customer_id","first_name","country","marital_status","gender"]]

In [68]:
fact_data = pd.merge(data,products,how="inner",on="product_key")[
    ["order_number","order_date","shipping_date","sales_amount","quantity","customer_id","first_name","country","gender","marital_status","product_number","product_name","category","subcategory","product_line"]]

In [69]:
data

,order_number,product_key,order_date,shipping_date,sales_amount,quantity,customer_id,first_name,country,marital_status,gender
0,SO54496,282,2013-03-16,2013-03-23,25,1,16399,Arturo,Germany,Single,Male
1,SO54496,289,2013-03-16,2013-03-23,5,1,16399,Arturo,Germany,Single,Male
2,SO54496,259,2013-03-16,2013-03-23,2,1,16399,Arturo,Germany,Single,Male
3,SO54497,174,2013-03-16,2013-03-23,22,1,20280,Joshua,Canada,Single,Male
4,SO54497,280,2013-03-16,2013-03-23,9,1,20280,Joshua,Canada,Single,Male
...,...,...,...,...,...,...,...,...,...,...,...
60393,SO54494,259,2013-03-16,2013-03-23,2,1,22278,Mariah,Canada,Single,Female
60394,SO54495,289,2013-03-16,2013-03-23,5,1,14749,Jose,United States,Married,Male
60395,SO54495,244,2013-03-16,2013-03-23,35,1,14749,Jose,United States,Married,Male
60396,SO54495,248,2013-03-16,2013-03-23,50,1,14749,Jose,United States,Married,Male
60397,SO54495,166,2013-03-16,2013-03-23,9,1,14749,Jose,United States,Married,Male

In [70]:
fact_data

,order_number,order_date,shipping_date,sales_amount,quantity,customer_id,first_name,country,gender,marital_status,product_number,product_name,category,subcategory,product_line
0,SO54496,2013-03-16,2013-03-23,25,1,16399,Arturo,Germany,Male,Single,TI-M267,LL Mountain Tire,Accessories,Tires and Tubes,Mountain
1,SO54496,2013-03-16,2013-03-23,5,1,16399,Arturo,Germany,Male,Single,TT-M928,Mountain Tire Tube,Accessories,Tires and Tubes,Mountain
2,SO54496,2013-03-16,2013-03-23,2,1,16399,Arturo,Germany,Male,Single,PK-7098,Patch Kit/8 Patches,Accessories,Tires and Tubes,Other Sales
3,SO54497,2013-03-16,2013-03-23,22,1,20280,Joshua,Canada,Male,Single,FE-6654,Fender Set - Mountain,Accessories,Fenders,Mountain
4,SO54497,2013-03-16,2013-03-23,9,1,20280,Joshua,Canada,Male,Single,SO-R809-M,Racing Socks- M,Clothing,Socks,Road
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60393,SO54494,2013-03-16,2013-03-23,2,1,22278,Mariah,Canada,Female,Single,PK-7098,Patch Kit/8 Patches,Accessories,Tires and Tubes,Other Sales
60394,SO54495,2013-03-16,2013-03-23,5,1,14749,Jose,United States,Male,Married,TT-M928,Mountain Tire Tube,Accessories,Tires and Tubes,Mountain
60395,SO54495,2013-03-16,2013-03-23,35,1,14749,Jose,United States,Male,Married,HL-U509,Sport-100 Helmet- Black,Accessories,Helmets,Other Sales
60396,SO54495,2013-03-16,2013-03-23,50,1,14749,Jose,United States,Male,Married,LJ-0192-L,Long-Sleeve Logo Jersey- L,Clothing,Jerseys,Other Sales
60397,SO54495,2013-03-16,2013-03-23,9,1,14749,Jose,United States,Male,Married,CA-1098,AWC Logo Cap,Clothing,Caps,Other Sales

In [71]:
fact_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 60398 entries, 0 to 60397
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_number    60398 non-null  str
 1   order_date      60379 non-null  str
 2   shipping_date   60398 non-null  str
 3   sales_amount    60398 non-null  int64
 4   quantity        60398 non-null  int64
 5   customer_id     60398 non-null  int64
 6   first_name      60398 non-null  str
 7   country         59527 non-null  str
 8   gender          60365 non-null  str
 9   marital_status  60398 non-null  str
 10  product_number  60398 non-null  str
 11  product_name    60398 non-null  str
 12  category        60398 non-null  str
 13  subcategory     60398 non-null  str
 14  product_line    60398 non-null  str
dtypes: int64(3), str(12)
memory usage: 6.9 MB

In [72]:
fact_data["order_date"] = pd.to_datetime(fact_data["order_date"])

In [66]:
fact_data

,order_number,order_date,shipping_date,sales_amount,quantity,customer_id,first_name,country,gender,marital_status,product_number,product_name,category,subcategory,product_line,year,month
0,SO54496,2013-03-16,2013-03-23,25,1,16399,Arturo,Germany,Male,Single,TI-M267,LL Mountain Tire,Accessories,Tires and Tubes,Mountain,2013,3
1,SO54496,2013-03-16,2013-03-23,5,1,16399,Arturo,Germany,Male,Single,TT-M928,Mountain Tire Tube,Accessories,Tires and Tubes,Mountain,2013,3
2,SO54496,2013-03-16,2013-03-23,2,1,16399,Arturo,Germany,Male,Single,PK-7098,Patch Kit/8 Patches,Accessories,Tires and Tubes,Other Sales,2013,3
3,SO54497,2013-03-16,2013-03-23,22,1,20280,Joshua,Canada,Male,Single,FE-6654,Fender Set - Mountain,Accessories,Fenders,Mountain,2013,3
4,SO54497,2013-03-16,2013-03-23,9,1,20280,Joshua,Canada,Male,Single,SO-R809-M,Racing Socks- M,Clothing,Socks,Road,2013,3

In [73]:
fact_data["shipping_date"] = pd.to_datetime(fact_data["shipping_date"])

In [74]:
fact_data["year"] = fact_data["order_date"].dt.year
fact_data["month"] = fact_data["order_date"].dt.month

In [82]:
fact_data.groupby(["year","month_name"])["sales_amount"].sum()

year    month_name
2010.0  dec             43419
2011.0  Apr            502042
        Feb            466307
        Jan            469795
        Jun            737793
        Mar            485165
        May            561647
        aug            614516
        dec            669395
        jul            596710
        nov            660507
        oct            708164
        sep            603047
2012.0  Apr            400324
        Feb            506992
        Jan            495363
        Jun            555142
        Mar            373478
        May            358866
        aug            523887
        dec            624454
        jul            444533
        nov            537918
        oct            535125
        sep            486149
2013.0  Apr           1045860
        Feb            771218
        Jan            857758
        Jun           1642948
        Mar           1049732
        May           1284456
        aug           1545910
        dec           1874128
        jul           1371595
        nov           1780688
        oct           1673261
        sep           1447324
2014.0  Jan             45642
Name: sales_amount, dtype: int64

In [76]:
fact_data["sales_amount"].sum()

np.int64(29356250)

In [78]:
month_map = {
    1:"Jan",2:"Feb",3:"Mar",4:"Apr",5:"May",6:"Jun",7:"jul",8:"aug",9:"sep",10:"oct",11:"nov",12:"dec"
}

In [80]:
fact_data["month_name"] = fact_data["month"].map(month_map)

In [98]:
f_data = fact_data[
    (fact_data["sales_amount"]==fact_data["sales_amount"].min())
                            &    
    (fact_data["sales_amount"].notna())]

In [102]:
f_data["sales_amount"].notna().value_counts()

sales_amount
True    3191
Name: count, dtype: int64