<h1><strong>What are missing values?</strong></h1>

We ecounter cells that are empty, null or undefined. These are called missing values - data point that were expected but were not recorded.

In python and pandas, missing values appear as NaN (Not a Number), None, or somtime as string like "N/A", "-" or "unknown" that must be manually converted .

<h2><strong>What missing values occurs </strong></h2>

- Survey non-response
- System failure
- Data entry errors
- Not applicable
- Deliberate omission
- Data migration

<h2><strong>Types of missing values</strong></h2>

- MCAR - Missing completely at random
- MAR - Missing at random
- MNAR - Missing not at random

<h2><strong>1. MCAR(Missing completely at random)</strong></h2>

The probability of a value being missed has absolutely no relationship with any variable in the dataset.

<h2><strong>2. MAR(Missing at Random)</strong></h2>

The missingness is related to observed data, but not the missing values themselves.

<h2><strong>3. MNAR(Missing not at random)</strong></h2>

the missingness depends on the observed value itself. This is hardest to handle.

<h1><strong>Methods for handling missing values</strong></h1>


1. Removing missing values(Deletion technique)

    1.1 Row Deletion(Listwise Deletion)<br>
    1.2 Column Deletion(Drop features)<br>

2. Imputation

    2.1 Univariate Imputation<br>
        2.1.1 Numerical Value Imputation<br>
        2.1.2 Categorical value Imputation<br>
    2.2 Multivariate Imputation<br>
        2.2.1 KNN-Imputer<br>
        2.2.2 Iterative Imputer

In [2]:
pip install pandas

Collecting pandas
  Downloading pandas-3.0.2-cp311-cp311-macosx_11_0_arm64.whl.metadata (79 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.4.4-cp311-cp311-macosx_14_0_arm64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/dhruv/Library/Python/3.11/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/dhruv/Library/Python/3.11/lib/python/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.2-cp311-cp311-macosx_11_0_arm64.whl (9.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 4.5 MB/s  0:00:02 eta 0:00:01
Downloading numpy-2.4.4-cp311-cp311-macosx_14_0_arm64.whl (5.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 3.0 MB/s  0:00:01 eta 0:00:01
Installing collected packages: numpy, pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [pandas]2m1/2 [pandas]
Successfully installed numpy-2.4.4 pandas-3.0.2
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd
import numpy as np

data = {
    'Name':["Rohan","Krish","Bob","Sohit","Kashish","Mayank"],
    'Age':[24,np.nan,34,23,np.nan,40],
    'Score':[85,90,np.nan,88,92,95],
    'Attendance':[100,90,80,np.nan,90,85]
}



df = pd.DataFrame(data)

ModuleNotFoundError: No module named 'pandas'

In [6]:
df

      Name   Age  Score  Attendance
0    Rohan  24.0   85.0       100.0
1    Krish   NaN   90.0        90.0
2      Bob  34.0    NaN        80.0
3    Sohit  23.0   88.0         NaN
4  Kashish   NaN   92.0        90.0
5   Mayank  40.0   95.0        85.0

In [5]:
df.isnull().sum()

Name          0
Age           2
Score         1
Attendance    1
dtype: int64

<h2><strong> Rows Deletion</strong></h2>

<h3><strong>When it is good to use?</strong></h3>

- Low percentage: If < 5% data is missing
- MCAR: The missingness has no hidden pattern.
- Large Dataset: If you have 1 million rows, losing 1000 wont hurt your model's perfomance.

<h3><strong>When not to use it?</strong></h3>

- Small Dataset: If you only have 100 rows, every single row is precious
- Bias Risk: If only "High income" individuals refused to answer the survey, dropping those rows removes your "High income" representation entirely.

In [7]:
df_dropped = df.dropna()

In [8]:
df_dropped

     Name   Age  Score  Attendance
0   Rohan  24.0   85.0       100.0
5  Mayank  40.0   95.0        85.0

If it is in subset.. then it will be removed

In [11]:
df_subset = df.dropna(subset=['Score','Attendance'])

In [12]:
df_subset

      Name   Age  Score  Attendance
0    Rohan  24.0   85.0       100.0
1    Krish   NaN   90.0        90.0
4  Kashish   NaN   92.0        90.0
5   Mayank  40.0   95.0        85.0

Keep rows with at least k non-NaN value.

In [30]:
df_thresh = df.dropna(thresh=3,axis=0)

In [32]:
dt = {
    "A":[1,np.nan,3,np.nan],
    "B":[4,np.nan,np.nan,np.nan],
    "C":[7,8,9,np.nan]
}

df1 = pd.DataFrame(dt)

In [36]:
df1

     A    B    C
0  1.0  4.0  7.0
1  NaN  NaN  8.0
2  3.0  NaN  9.0
3  NaN  NaN  NaN

In [39]:
df_thr = df1.dropna(thresh=3)
df_thr

     A    B    C
0  1.0  4.0  7.0

In [50]:
df_thresh = df.dropna(thresh=3)

In [51]:
df_thresh

      Name   Age  Score  Attendance
0    Rohan  24.0   85.0       100.0
1    Krish   NaN   90.0        90.0
2      Bob  34.0    NaN        80.0
3    Sohit  23.0   88.0         NaN
4  Kashish   NaN   92.0        90.0
5   Mayank  40.0   95.0        85.0

<h2><strong>Column Deletion</strong></h2>

<h3><strong>When it is good to Use</strong></h3>

- High missingness: eg. > 50, 60 ,....
- Irrelevance: If the feature isn't crucial for the prediction

<h3><strong>When it is not recommended</strong></h3>

- Domain Importance

In [52]:
df['Notes'] = [np.nan,"Good",np.nan,np.nan,np.nan,"Agerage"]

In [53]:
df

      Name   Age  Score  Attendance    Notes
0    Rohan  24.0   85.0       100.0      NaN
1    Krish   NaN   90.0        90.0     Good
2      Bob  34.0    NaN        80.0      NaN
3    Sohit  23.0   88.0         NaN      NaN
4  Kashish   NaN   92.0        90.0      NaN
5   Mayank  40.0   95.0        85.0  Agerage

In [58]:
missing_pct = df.isnull().sum()/len(df) * 100

In [63]:
missing_pct.values

array([ 0.        , 33.33333333, 16.66666667, 16.66666667, 66.66666667])

In [67]:
limit = 30

cols_to_drop = missing_pct[missing_pct>limit].index

df_reduced = df.drop(columns=cols_to_drop)

In [68]:
df_reduced

      Name  Score  Attendance
0    Rohan   85.0       100.0
1    Krish   90.0        90.0
2      Bob    NaN        80.0
3    Sohit   88.0         NaN
4  Kashish   92.0        90.0
5   Mayank   95.0        85.0

In [ ]:
-