<center><h1 style="color:cyan;"><strong>Pandas Tutorial</strong></h1></center>

Pandas is a Python library for data analysis and data manipulation tasks. It works with many different types of data sets such as comma-separated values (CSV) files, Excel files, extensible markup language (XML) files, JavaScript object notation (JSON) files and relational database tables.

In pandas we are given type of datastructure

- 1D datastructure = Series
- 2D datastructure = DataFrame

column -> field -> label
row -> record

In [22]:
{
        [
            "Mr. Owen Harris",
            "Mr. William Henry",
            " Miss Elizabeth",
        ],
         [22, 35, 58],
        ["male", "male", "female"],
}

TypeError: cannot use 'list' as a set element (unhashable type: 'list')

In [2]:
print(type(d))

<class 'dict'>

In [3]:
!pip3 install pandas

Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (3.0.0)
Requirement already satisfied: numpy>=2.3.3 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/dhruv/Library/Python/3.14/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/dhruv/Library/Python/3.14/lib/python/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

{
    "name":"Rohit",
    "Age",23,
    "salary":45000
},
{
    "name":"Shreya",
    "Age",22,
    "salary":38000
}

In [4]:
import pandas as pd

1D datastructure(Series)

In [5]:
sr = pd.Series([34,45,23,65])

In [8]:
print(type(sr))

<class 'pandas.Series'>

2D datastructure(DataFrame)

In [19]:
df = pd.DataFrame(d)

In [20]:
print(df)
print(type(df))

                Name  Age     Sex
0    Mr. Owen Harris   22    male
1  Mr. William Henry   35    male
2     Miss Elizabeth   58  female
<class 'pandas.DataFrame'>

load csv in pandas

In [23]:
df = pd.read_csv('fact_sales.csv')

In [27]:
df.head(10)

,order_number,product_key,customer_key,order_date,shipping_date,due_date,sales_amount,quantity,price
0,SO54496,282,5400,2013-03-16,2013-03-23,2013-03-28,25,1,25
1,SO54496,289,5400,2013-03-16,2013-03-23,2013-03-28,5,1,5
2,SO54496,259,5400,2013-03-16,2013-03-23,2013-03-28,2,1,2
3,SO54497,174,9281,2013-03-16,2013-03-23,2013-03-28,22,1,22
4,SO54497,280,9281,2013-03-16,2013-03-23,2013-03-28,9,1,9
5,SO54498,174,4825,2013-03-16,2013-03-23,2013-03-28,22,1,22
6,SO54498,277,4825,2013-03-16,2013-03-23,2013-03-28,54,1,54
7,SO54499,289,4286,2013-03-16,2013-03-23,2013-03-28,5,1,5
8,SO54499,246,4286,2013-03-16,2013-03-23,2013-03-28,35,1,35
9,SO54500,289,1472,2013-03-16,2013-03-23,2013-03-28,5,1,5

In [28]:
df.tail(15)

,order_number,product_key,customer_key,order_date,shipping_date,due_date,sales_amount,quantity,price
60383,SO54490,248,9280,2013-03-16,2013-03-23,2013-03-28,50,1,50
60384,SO54490,235,9280,2013-03-16,2013-03-23,2013-03-28,24,1,24
60385,SO54491,295,1166,2013-03-16,2013-03-23,2013-03-28,5,1,5
60386,SO54491,168,1166,2013-03-16,2013-03-23,2013-03-28,8,1,8
60387,SO54492,295,5886,2013-03-16,2013-03-23,2013-03-28,5,1,5
60388,SO54492,246,5886,2013-03-16,2013-03-23,2013-03-28,35,1,35
60389,SO54493,289,4881,2013-03-16,2013-03-23,2013-03-28,5,1,5
60390,SO54493,168,4881,2013-03-16,2013-03-23,2013-03-28,8,1,8
60391,SO54493,260,4881,2013-03-16,2013-03-23,2013-03-28,120,1,120
60392,SO54494,289,11279,2013-03-16,2013-03-23,2013-03-28,5,1,5
60393,SO54494,259,11279,2013-03-16,2013-03-23,2013-03-28,2,1,2
60394,SO54495,289,3750,2013-03-16,2013-03-23,2013-03-28,5,1,5
60395,SO54495,244,3750,2013-03-16,2013-03-23,2013-03-28,35,1,35
60396,SO54495,248,3750,2013-03-16,2013-03-23,2013-03-28,50,1,50
60397,SO54495,166,3750,2013-03-16,2013-03-23,2013-03-28,9,1,9

In [32]:
print(df.columns)

Index(['order_number', 'product_key', 'customer_key', 'order_date',
       'shipping_date', 'due_date', 'sales_amount', 'quantity', 'price'],
      dtype='str')

In [33]:
df.dtypes

order_number       str
product_key      int64
customer_key     int64
order_date         str
shipping_date      str
due_date           str
sales_amount     int64
quantity         int64
price            int64
dtype: object

In [34]:
df.info

<bound method DataFrame.info of       order_number  product_key  customer_key  order_date shipping_date  \
0          SO54496          282          5400  2013-03-16    2013-03-23
1          SO54496          289          5400  2013-03-16    2013-03-23
2          SO54496          259          5400  2013-03-16    2013-03-23
3          SO54497          174          9281  2013-03-16    2013-03-23
4          SO54497          280          9281  2013-03-16    2013-03-23
...            ...          ...           ...         ...           ...
60393      SO54494          259         11279  2013-03-16    2013-03-23
60394      SO54495          289          3750  2013-03-16    2013-03-23
60395      SO54495          244          3750  2013-03-16    2013-03-23
60396      SO54495          248          3750  2013-03-16    2013-03-23
60397      SO54495          166          3750  2013-03-16    2013-03-23

         due_date  sales_amount  quantity  price
0      2013-03-28            25         1     25
1      2013-03-28             5         1      5
2      2013-03-28             2         1      2
3      2013-03-28            22         1     22
4      2013-03-28             9         1      9
...           ...           ...       ...    ...
60393  2013-03-28             2         1      2
60394  2013-03-28             5         1      5
60395  2013-03-28            35         1     35
60396  2013-03-28            50         1     50
60397  2013-03-28             9         1      9

[60398 rows x 9 columns]>

In [41]:
df['sales_amount'].values.mean()

np.float64(486.04672340143713)

In [42]:
df.ndim

2

In [43]:
df.size

543582

In [44]:
df.shape

(60398, 9)

In [46]:
df.head().memory_usage

<bound method DataFrame.memory_usage of   order_number  product_key  customer_key  order_date shipping_date  \
0      SO54496          282          5400  2013-03-16    2013-03-23
1      SO54496          289          5400  2013-03-16    2013-03-23
2      SO54496          259          5400  2013-03-16    2013-03-23
3      SO54497          174          9281  2013-03-16    2013-03-23
4      SO54497          280          9281  2013-03-16    2013-03-23

     due_date  sales_amount  quantity  price
0  2013-03-28            25         1     25
1  2013-03-28             5         1      5
2  2013-03-28             2         1      2
3  2013-03-28            22         1     22
4  2013-03-28             9         1      9  >

In [49]:
df['sales_amount'].astype('float64')

0        25.0
1         5.0
2         2.0
3        22.0
4         9.0
         ...
60393     2.0
60394     5.0
60395    35.0
60396    50.0
60397     9.0
Name: sales_amount, Length: 60398, dtype: float64

In [51]:
df.loc[0]

order_number        SO54496
product_key             282
customer_key           5400
order_date       2013-03-16
shipping_date    2013-03-23
due_date         2013-03-28
sales_amount             25
quantity                  1
price                    25
Name: 0, dtype: object

In [54]:
df.head(2)

,order_number,product_key,customer_key,order_date,shipping_date,due_date,sales_amount,quantity,price
0,SO54496,282,5400,2013-03-16,2013-03-23,2013-03-28,25,1,25
1,SO54496,289,5400,2013-03-16,2013-03-23,2013-03-28,5,1,5

In [52]:
df1 = pd.DataFrame(
    [[1, 2], [4, 5], [7, 8]],
    index=["cobra", "viper", "sidewinder"],
    columns=["max_speed", "shield"],
)

In [53]:
df1

            max_speed  shield
cobra               1       2
viper               4       5
sidewinder          7       8

In [58]:
df1.loc["cobra"]

max_speed    1
shield       2
Name: cobra, dtype: int64

In [60]:
df1.iloc[0]

max_speed    1
shield       2
Name: cobra, dtype: int64

In [61]:
df2 = pd.DataFrame({
    'col1':[1,2],
    'col2':[3,4]
})

In [66]:
df2.insert(1,"col4",[9,0])

In [67]:
df2

   col3  col4  col1  col2
0     5     9     1     3
1     6     0     2     4